Demos/03-app/EmailMetrics/EmailMetrics/Models/EmailMetric.cs
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EmailMetrics.Models
{
    public class EmailMetric
    {
        public string Email;
        public double RecipientsToEmail;
    }
}

Demos/03-app/EmailMetrics/EmailMetrics/Controllers/EmailMetricsController.cs
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Newtonsoft.Json.Linq;
using System.Configuration;
using System.IO;
using System.Threading.Tasks;

namespace EmailMetrics.Controllers
{
    public class EmailMetricsController : Controller
    {
        CloudStorageAccount _storageAccount;
        CloudBlobClient _storageClient;
        CloudBlobContainer _storageContainer;

        // GET: EmailMetrics
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost, ActionName("ShowMetrics")]
        [ValidateAntiForgeryToken]
        public ActionResult ShowMetrics()
        {
            var emailMetrics = ProcessBlobFiles();

            return View(emailMetrics);
        }

        private void ProcessBlobEmails(List<Models.EmailMetric> emailMetrics, CloudBlob emailBlob)
        {
            using (var reader = new StreamReader(emailBlob.OpenRead()))
            {
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    var jsonObj = JObject.Parse(line);

                    // extract sender
                    var sender = jsonObj.SelectToken("Sender.EmailAddress.Address")?.ToString();

                    // extract and count up recipients
                    var totalRecipients = 0;
                    totalRecipients += jsonObj.SelectToken("ToRecipients").Children().Count();
                    totalRecipients += jsonObj.SelectToken("CcRecipients").Children().Count();
                    totalRecipients += jsonObj.SelectToken("BccRecipients").Children().Count();

                    var emailMetric = new Models.EmailMetric();
                    emailMetric.Email = sender;
                    emailMetric.RecipientsToEmail = totalRecipients;

                    // if already have this sender... 
                    var existingMetric = emailMetrics.FirstOrDefault(metric => metric.Email == emailMetric.Email);
                    if (existingMetric != null)
                    {
                        existingMetric.RecipientsToEmail += emailMetric.RecipientsToEmail;
                    }
                    else
                    {
                        emailMetrics.Add(emailMetric);
                    }
                }
            }
        }

        private List<Models.EmailMetric> ProcessBlobFiles()
        {
            var emailMetrics = new List<Models.EmailMetric>();

            // connect to the storage account
            _storageAccount = CloudStorageAccount.Parse(ConfigurationManager.AppSettings["AzureStorageConnectionString-1"]);
            _storageClient = _storageAccount.CreateCloudBlobClient();

            // connect to the container
            _storageContainer = _storageClient.GetContainerReference("maildump");

            // get a list of all emails
            var blobResults = _storageContainer.ListBlobs();

            // process each email
            foreach (IListBlobItem blob in blobResults)
            {
                if (blob.GetType() == typeof(CloudBlockBlob))
                {
                    var cloudBlob = (CloudBlockBlob)blob;
                    var blockBlob = _storageContainer.GetBlobReference(cloudBlob.Name);

                    ProcessBlobEmails(emailMetrics, blockBlob);
                }
            }

            return emailMetrics;
        }
    }
}

Demos/03-app/EmailMetrics/EmailMetrics/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmailMetrics.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Demos/03-app/EmailMetrics/EmailMetrics/Views/EmailMetrics/Index.cshtml
@* Copyright (c) Microsoft Corporation. All rights reserved. *@
@* Licensed under the MIT license. *@

@{
    ViewBag.Title = "Index";
}

<h2>Email Metrics</h2>

    This application will look at the email data for emails extracted to the Azure Blob Storage account and display the total number of recipients from each sender.

@using (Html.BeginForm("ShowMetrics", "EmailMetrics", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div>
        <button type="submit">View email metrics</button>
    </div>

    <div>
        <em>Please be patient as this can take a few moments to calculate depending on the size of the exported data...</em>
    </div>
}

Demos/03-app/EmailMetrics/EmailMetrics/Views/EmailMetrics/ShowMetrics.cshtml
@* Copyright (c) Microsoft Corporation. All rights reserved. *@
@* Licensed under the MIT license. *@

@model IEnumerable<EmailMetrics.Models.EmailMetric>

@{
    ViewBag.Title = "ShowMetrics";
}

<h2>Email Metrics</h2>

<table class="table">
    <tr>
        <th>Sender</th>
        <th>Number of Recipients</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Email)</td>
            <td>@Html.DisplayFor(modelItem => item.RecipientsToEmail)</td>
        </tr>
    }

</table>

Demos/03-app/EmailMetrics/EmailMetrics/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Demos/03-app/EmailMetrics/EmailMetrics/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Demos/03-app/EmailMetrics/EmailMetrics/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Demos/03-app/EmailMetrics/EmailMetrics/Views/Shared/_Layout.cshtml
@* Copyright (c) Microsoft Corporation. All rights reserved. *@
@* Licensed under the MIT license. *@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Email Metrics", "Index", "EmailMetrics")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>